@Identity_HostAddress = http://localhost:5148

POST {{Identity_HostAddress}}/api/account/SignUp
Accept: application/json
Content-Type: application/json
{
  "account": "Audin",
  "password": "123"
}
###


POST {{Identity_HostAddress}}/api/account/SignIn
Accept: application/json
Content-Type: application/json
{
  "account": "Audin",
  "password": "123"
}
###

GET {{Identity_HostAddress}}/api/account/CheckJWT
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjYiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiQXVkaW4iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJOb3JtYWxVc2VyIiwiZXhwIjoxNzgyNTc1MTk2LCJpc3MiOiJBdWRpbiBUZXN0IiwiYXVkIjoiQXBpIENsaWVudCJ9.aDes2zK1EyGucBC_p-3O6aSc-IZOMSf7nDbONeqA-0o
###